### ISSUE TITLE
Disable backtick references

### ISSUE THREAD

**Issue by craigbarnes** [lunarmodules/ldoc#100]
Is there any way to disable automatic linking of "recognized" words inside backticks?

I have a [readme](http://cra.igbarn.es/projects/lua-gumbo/topics/README.md.html) file that contains a few occurrences of ``type`` and LDoc is turning them into unwanted links to the Lua reference manual.

**Edit**: the readme link above no longer demonstrates what I describe, since I did a little `sed` post-processing.

**Comment by alerque** [comment]
Duplicate of #81, still not addressed.

**Comment by alerque** [comment]
Correction, #81 is related but would only be resolved by specific filtering of backticks.

In the mean time there **was** a new config option added to disable them completely as this issue requested, set `backtick_references = false` in your config.
