### ISSUE TITLE
@param[type=number|table] doesn't work, but that isn't clear in the documentation

### ISSUE THREAD

**Issue by andrewstarks** [lunarmodules/ldoc#104]
So, if I type `@tparam bool|number|table`, i get the expected result.

If I am using the alternate `@param[type=bool|number|table]` syntax, it does not work. It produces confusing and broken output.

That's fine, except that the manual is not clear about it. Under [Tag Modifiers](http://stevedonovan.github.io/ldoc/topics/doc.md.html#Tag_Modifiers), the manual talks about the `@param[type=number]` style. Then it talks about the `@tparam` shortcut. Then it talks about the various styles of optional arguments. Here is my suggested rewrite:

> Any tag may have tag modifiers. For instance, you may say @param[type=number] and this associates the modifier type with value number with this particular param tag. A shorthand has been introduced for this common case, which is @tparam <type> <parmname> <comment>; in the same way @treturn is defined.
> This is useful for larger projects where you want to provide the argument and return value types for your API, in a structured way that can be easily extracted later.
> 
> Another advantage to the @tparam form is that types can also be combined, so that “?string|number” means “ether a string or a number”; “?string” is short for “?|nil|string”. However, for this last case you should usually use the opt modifier discussed below.
> 
> Remember, @param[type=<name>] only accepts one type name, so if your arguments can accept more than one type, then @tparam is the way to go.
> ....

---

**Comment by alerque** [comment]
The `tparam` alias was teaked and documentation editing since this issue was reported. If something is still not clear feel free to comment for re-evaluation or sumbit a PR to the docs.
