### ISSUE TITLE
class vs object method heuristic is not working consistently for @classmod files

### ISSUE THREAD

**Issue by gvvaughan** [lunarmodules/ldoc#111]
In lua-stdlib, clone method markup is handled correctly:

```
 91 --- Clone an object.
 92 --
 93 -- Objects are usually cloned by calling a prototype directly, so this
 94 -- method is rarely used explicitly.
 95 -- @param              ... arguments for _init
 96 -- @treturn std.object     a clone of `prototype`, adjusted
 97 --   according to the rules above, and sharing a metatable where possible
 98 -- @see __call
 99 local function clone (self, ...)
```

http://rrthomas.github.io/lua-stdlib/classes/std.object.html#std.object:clone

But, the `self` parameter is not removed from the similar totable method:

```
194 --- Return a new table with a shallow copy of all non-private fields
195 -- in object, where private fields have keys prefixed with "_".
196 -- @treturn table raw (non-object) table of object fields
197 local function totable (self)
```

http://rrthomas.github.io/lua-stdlib/classes/std.object.html#std.object:totable

And then, even without an undocumented `self` parameter, the type class method appears in the generated docs as an object method (with a `:` rather than a `.`):

```
 79 -- @function type
 80 -- @tparam  std.object o  an object
 81 -- @treturn string        type of the object
 82 local function object_type (o)
```

http://rrthomas.github.io/lua-stdlib/classes/std.object.html#std.object:type

**Comment by alerque** [comment]
The heuristics for class vs object method were fiddled with in the v1.5.0 release. I messed with your MWE's as best I could recreate them (since they are not complete standalone code samples) and the issue seems to be corrected. If I'm missing something please do feel free to comment for re-evaluation.
