### ISSUE TITLE
boilerplate option inconsistent

### ISSUE THREAD

**Issue by dirkfeytons** [lunarmodules/ldoc#123]
Using LDoc f60e6d419733826e869b1ed845a23a21e17aa7e0

I have a file `test.c` with following contents:

``` C
/** boiler plate
 ******************************************************************************/

/**
 * My Module.
 * @module my.lib
 */

#include <lua.h>
#include <lauxlib.h>

static int l_my_func(lua_State *L)
{
  return 0;
} 
```

and a `config.ld` with a simple

``` Lua
boilerplate = true
```

Invoking `ldoc . test.c` fails with `.../test.c:9: Module already declared!` but invoking `ldoc -B . test.c` everything works.
If I change the first line in `test.c` to `/* boiler plate` then both invocations work.

**Comment by alerque** [comment]
I just tested the MWE here and the previously merged PR seems to have fixed this.
