### ISSUE TITLE
Mailing list?

### ISSUE THREAD

**Issue by etc0de** [lunarmodules/LDoc#124]
Hi guys,

I have multiple issues but I suspect they may be entirely my fault. However, there doesn't appear to be any place where I could ask except here, but support tickets seem to be a bit out of place. Have you ever considered setting up a mailing list?

Nevertheless, let me also mention what I'm stuck with:
- I can't get custom sorting to work (with an own sorting function) although it's apparently supported. See issue 64
- With the newest git update, a lot of valid(?) @ references suddenly turned into ???. Most specifically, for a module blitwizard.somemodule with class type mytype, @{blitwizard.somemodule.mytype.somemember} no longer works (inside that module), and all @{blitwizard.othermodule.othertype.othermember} also stopped working. Only short references like @{mytype.somemember} still work. Is this my mistake, did something change here?

Regards,

**Comment by alerque** [comment]
This is the right place for bug reports. If there is a bug, there should be an issue to track it. If there are 100 bugs there should be 100 issues. No there is no mailing list (that I'm aware of). Hence *this* issue is resolved. But the other thing about bug tracking is that mixing up a bunch of different issues really isn't a good idea. Besides the question that is the main point of the issue it looks like you were having other trouble. If that's still unresolved by the current release please open a specific report about it. Thanks.
