### ISSUE TITLE
@public/@private tags

### ISSUE THREAD

**Issue by dirkfeytons** [lunarmodules/ldoc#133]
I would like to have a way to somehow tag a non-local function as 'public' or 'private'. Idea would be that while a function is exported from a module it is not always the intention that third party code is supposed to call it. Or it's an experimental feature that is not ready yet for mass usage.
The custom tags patch allows me to add such tags but I think it doesn't allow me to exclude things from the documentation based on the presence of a certain tag.

**Comment by alerque** [comment]
This seems to have been addressed, feel free to comment if the `@local` tag and using or not using the `--all` argument doesn't serve your use case.
