### ISSUE TITLE
Block comment boilerplate parsed wrongly

### ISSUE THREAD

**Issue by dirkfeytons** [lunarmodules/ldoc#137]
My Lua file starts with the following boilerplate structure:

```
--[[
/************** COPYRIGHT AND CONFIDENTIALITY INFORMATION *********************
<more stuff here>
 ******************************************************************************/
--]]

---
-- My module
-- @module mymod

<actual code>
```

However, LDoc complains that it can't find a module definition, despite using the `-B` command line option. I did some debugging and it seems that when lexing in `lexer.scan()` it does this on a line-by-line basis (`file:read()`) so of course the block comment pattern in `lexer.lua()` doesn't match and it thinks it's a line comment. That line is thrown away as boilerplate but then the parsing gets confused by the next lines.

**Comment by alerque** [comment]
Fixed in 60c6e79.
