### ISSUE TITLE
Allow pure text pages (e.g. for FAQ)

### ISSUE THREAD

**Issue by ghost** [lunarmodules/ldoc#153]
I suggest introducing a new tag, e.g. @page or similar, which allows to write text for a dedicated page with markdown formatting.

The page should be linked where the "Index" link is with the given name.

This would be very useful for writing up generic FAQ sections which aren't specifically tied to some function or module, but still to the project as a whole. It would elevate the generated documentation from a pure API definition to something more complete which can serve as full project documentation without any additional external files.

Additionally, I suggest a source code file parsed by ldoc should be allowed to contain just a doc comment with @page tag, and no module, so those FAQ articles can be kept in separate files if desired.

**Comment by alerque** [comment]
Already implemented. Further docs improvements always welcome.
