### ISSUE TITLE
docs missing from rock

### ISSUE THREAD

**Issue by Tieske** [lunarmodules/ldoc#155]
with luarocks the command;

```
luarocks doc ldoc
```

Shows only;

```
C:\Users\Thijs\Dropbox\Lua projects\corowatch>luarocks doc ldoc

Documentation files for ldoc 1.4.2-1
------------------------------------

C:/Program Files (x86)/LuaRocks/systree/lib/luarocks/rocks/ldoc/1.4.2-1/doc/
        config.ld
        doc.md

C:\Users\Thijs\Dropbox\Lua projects\corowatch>
```

Can the generated ldoc documentation be included in the package? so the command actually opens the documentation.

**Comment by alerque** [comment]
I don't know what release first featured this, but at least in the current v1.5.0 release it works as expected.
