### ISSUE TITLE
Summary line lost for classes documented with the @type tag

### ISSUE THREAD

**Issue by rolandyoung** [lunarmodules/ldoc#158]
A change introduced in commit 52e9b6f3 has the effect of setting the summary line to an empty string for classes defined with the @type tag. This has forced our project to revert LDoc to version 1.3.12

It appears that this can be fixed by simply deleting line 372 from ldoc/doc.lua, but I have not yet had the opportunity to try this against the test suite (we have installed the rock, not the full source)

**Comment by alerque** [comment]
Fixed in 3f32313.
