### ISSUE TITLE
Nested list with `markdown.lua`

### ISSUE THREAD

**Issue by aignas** [lunarmodules/LDoc#162]
I have a problem with this [file](https://github.com/Techniv/Licenses-for-GitHub/blob/master/GNU-GPL/V2/gpl-2.0.md). It has many indented nested lists, but the parser tries to interpret those as code blocks, which is wrong.

How could I fix it?

**Comment by jirutka** [comment]
I have the same problem. I’d like to use nested lists in my ldocs, but without success.

**Comment by elliottslaughter** [comment]
There must be some sort of pre-processing that's messing this up before it hits the markdown parser. I was able to run with the lunamark processor, and if I copy-and-paste the exact same contents into an independent markdown file it renders correctly.

Here are the input files I used for the comparison:

  * [in.lua](https://github.com/stevedonovan/LDoc/files/4484060/in.lua.txt) (note: rename to `.lua` when you download this, Github doesn't allow `.lua` attachments)
  * [in.md.txt](https://github.com/stevedonovan/LDoc/files/4484061/in.md.txt) (same, rename to `.md`)

You can see from the diff that the files are nearly identical:

```
$ diff -u in.lua in.md
--- in.lua	2020-04-15 15:44:06.000000000 -0700
+++ in.md	2020-04-15 15:43:58.000000000 -0700
@@ -1,4 +1,3 @@
---[[--
 Summary.
 
 *   List entry.
@@ -12,4 +11,3 @@
         with contents wrapped to next line.
 
 @module in
-]]
```

Command I ran:

```
ldoc -f lunamark in.lua
lunamark -t html in.md > in.html
```

Outputs:

  * [doc.tar.gz](https://github.com/stevedonovan/LDoc/files/4484065/doc.tar.gz) (output from `ldoc`)
  * [in.html.txt](https://github.com/stevedonovan/LDoc/files/4484066/in.html.txt) (output from `lunamark`, rename to `.html`)

When I look at the results, I see that (a) the nested list is flattened, and (b) some of the soft-wrapped lines have been converted to code blocks. But this isn't the case in the direct lunamark output, which suggests there's some sort of pre-processing going before the contents of the text are even hitting the markdown processor.

This is with lunamark but I get similar results with the other markdown processors.

**Comment by elliottslaughter** [comment]
The problem is here: https://github.com/stevedonovan/LDoc/blob/f91c3182cf0b3ac29a8f677491aa32493067b5e1/ldoc/markup.lua#L177

The code is using regular expressions to preprocess code blocks (either with ```` ``` ```` or via indentation). If you change that (and the preceding check for fenced blocks) to `if false` then you get back the markdown processor's default behavior.

As best I can tell, the purpose of the prettifier seems to be for code highlighting. I can think of a couple possible solutions to this:

1. Switch to a markdown processor like Pandoc that has built-in support for code highlighting, so that this no longer needs to be done as an independent processing step.
2. Switch to a client-side code highlighting library.
3. Change the prettifier to a post-processing pass instead of a pre-processing pass. At least lunamark appears to spit out the code as `<code>` blocks, which do not seem too difficult to parse, assuming there's a readily available HTML parser you can use. Though there may be some differences between the HTML that the various Markdown processors produce, so that might be a sticking point.
4. At the very least, add an option to disable this prettification, so that users can choose what set of features they want (full-featured Markdown vs code highlighting).

**Comment by elliottslaughter** [comment]
I pushed a workaround [here](https://github.com/elliottslaughter/LDoc/tree/pandoc) based on option (1) above. It would need a bit of CSS to get the code highlighting to show up in color, but otherwise it seems to be working. Not necessarily in a state I'd recommend merging, but it at least demonstrates that this can be done.

**Comment by elliottslaughter** [comment]
Ok, I pushed a workaround based on (4) to #326. This makes it possible to set `pretty="none"`, which should work for any Markdown parser, but obviously disables syntax highlighting if it's not natively supported by the Markdown parser itself.
