### ISSUE TITLE
Improve the `[opt]` behaviour.

### ISSUE THREAD

**Issue by aignas** [lunarmodules/ldoc#165]
At the moment if we pass `[opt]` to a parameter, it is assumed, that the parameter depends on the previous optional parameter, which is not allways the case. So let's assume we have a function definition:

```
--- A test function
-- @int[opt=2] a
-- @int[opt=3] b
function test(a, b)
-- ...
end
```

The function name which would be generated in this case would be `test([a, [b]])`, which according to [Wikipedia](http://en.wikipedia.org/wiki/Usage_message) should be understood, that the `b` parameter is dependent on the `a` parameter.

So the proposal is that the default behaviour of LDoc for the example above would be to interpret the function as `test([a], [b])` or `test([a, b])` and if we want to make optional parameters to depend on each other (i.e. output is `test([a, [b]])`), then we should have to use the code bellow:

```
--- A test function
-- @int[opt=2] a Some optional integer.
-- @int[opt=3, a] b Another optional integer, parsed only if `a` is given.
function test(a, b)
-- ...
end
```

One more suggestion since I am at it. Do you think it would be reasonable to have a `config.ld` option so that the default values for optional arguments would not be printed in the list of functions? For example this [example](http://stevedonovan.github.io/ldoc/examples/four/) contains default values for the optional parameters, but it would be better to have them shown in the function description as otherwise the function list can get crowded.

I have also noticed that an option such as `opt="a,b"` is only recognised as `"a`.

Thanks

**Comment by alerque** [comment]
Using the MWE from the original issue I get the expected `test ([a=2[, b=3]])`, so this apparently got addressed. Feel free to comment if anything is still not satisfactory.
