### ISSUE TITLE
[Bug Report] Using a referenced name seems to break

### ISSUE THREAD

**Issue by andrewstarks** [lunarmodules/ldoc#166]
Provided the following:

``` lua
 --[[---
Does some stuff.
@param @{request} A description.
@return @{reply} A description of the return value.
--]]
function my:thing(request)
end

--[[---
My request table
@table request
@param bla A description
--]]
--[[---
My reply table
@table reply
@param foo_field A description
--]]
```

I get:

**my:thing (request)**
Does some stuff.
**Parameters:**

request: } A description.

**Returns:**

reply A description of the return value.

---

Note that the error is in the request. When I cut/pasted, I see that the text doesn't _actually_ contain a ":" after request. It appears that the colon and style are part of CSS and not the returned value.

Is this a bug or an error on my part, which may be a sign of a need to trap this in a better way...?

**Comment by alerque** [comment]
Playing around with v1.5.0 and the MWE from this issue this appears to have been fixed. Feel free to comment if something is still not working as expected.
