### ISSUE TITLE
Plain text output

### ISSUE THREAD

**Issue by Xe** [lunarmodules/ldoc#168]
Is there a way to get plain text output from ldoc similar to [godoc](https://godoc.org/code.google.com/p/go.tools/cmd/godoc)?

**Comment by alerque** [comment]
Given existing per-module plain text, full Markdown, or HTML output and the existence of `pandoc` I don't feel like this is an urgent need. I can't even think of the use case here.

That being said if somebody does want to implement a new template that outputs plain text formatting for some use case I would be happy to facilitate it getting contributed.
