### ISSUE TITLE
Including last updated date in footer of HTML template (ldoc.ltp)

### ISSUE THREAD

**Issue by GrahamHannington** [lunarmodules/ldoc#170]
I'd like to append "on _yyyy-mm-dd_" to the "generated by LDoc _n.n.n_" text in the page footer.

Unfortunately (although, perhaps, understandably), the template is sandboxed. For example, I can't access os.date(). I get:

> attempt to index global 'os' (a nil value)

Is there any way to insert either the current date (that is, the date that LDoc built the output) or the last modified date of the source file (for example, the .md, .lua, or .c file) in the template, without resorting to forking LDoc? (It occurs to me that I could add this information as a property of the modules tables that the template can access.)

Added later: the last modified date of each source file is much more useful to me than the LDoc build date.

**Comment by alerque** [comment]
Fixed in bf11db2.
