### ISSUE TITLE
Extra space after `backtick_references`

### ISSUE THREAD

**Issue by blueyed** [lunarmodules/ldoc#172]
I came across issue #55 and set `backtick_references = true` (with `format` undefined), and noticed that there's an extra space after the linked identifier:

```
`awful.client.moveresize`(0, 0, 0, 5, c)
```

=>

```
<a href="../modules/awful.client.html#moveresize">awful.client.moveresize</a> </span>(<span class="number">0</span>,
```

This makes it unconvenient for copy'n'pasting, if you want to copy it as-is.

ldoc 1.4.2-1

**Comment by alerque** [comment]
Fixed in 2639dde.
