### ISSUE TITLE
Table documentation fails to handle keys like this: ['-p']

### ISSUE THREAD

**Issue by rtmclay** [lunarmodules/ldoc#179]
I have a table:

```lua
--- replacement table for version parts
replaceT = {
	pre     = "c",         -- marked as a candidate version
	['-p']  = "zfinal-",   -- marked as a patched version
	rc      = "c",         -- marked as a candidate version
}
```

The ['-p'] gets reported as '['  and no -p.  This is with ldoc 1.4.2

**Comment by alerque** [comment]
This has evidently been fixed because I setup an MWE with this exact table and get a properly documented `[-p]: marked as...` in the output fields from LDoc v1.5.0.
