### ISSUE TITLE
A reminder: add the two new files to the rockspec

### ISSUE THREAD

**Issue by mooffie** [lunarmodules/ldoc#189]
After a recent commit ldoc has two new files:

ldoc/html/_code_css.lua
ldoc/html/_reset_css.lua

They should be listed in some .rockspec file as well. I didn't know what procedure you follow for updating that file so I couldn't do that myself.

**Comment by alerque** [comment]
This was added to the dev rockspec and is featured in the latest v1.5.0 tagged rockspec as well.
