### ISSUE TITLE
hardcoded tempdir location breaks use of LDocs by multiple user accounts

### ISSUE THREAD

**Issue by gvvaughan** [lunarmodules/ldoc#195]
Running LDoc always leaves a /tmp/ldoc directory, which prevents other users from running ldoc until that directory is manually removed due to `cannot write to /tmp/ldoc` error.

LDoc should certainly remove this tempdir before exiting, and ideally would name it using a unique suffix, such as the process-id or even a random number so that two or more users can run LDoc concurrently.

I dug around to try to find where this happens, but got lost in penlight before I was able to track it down.

**Comment by stevedonovan** [comment]
Good point, Gary!  Penlight is the immediate culprit, but the main
discipline we want is that it's (a) a semi-random number and (b) is removed
afterwards. This should be straightforward.  I'll have a look once I'm back
in the country that contains all my machines.

**Comment by gvvaughan** [comment]
awesome, tx :-)

**Comment by stevedonovan** [comment]
Sorry, I'm a really bad BDFL ;)  Commit adds a mangled version of user's home directory to 'ldoc'

**Comment by gvvaughan** [comment]
life often gets in the way :-) Thanks for the first part of the fix.

Do we also still want to clear up the file droppings at the end of a successful ldocs run?

**Comment by alerque** [comment]
Fixed in 2f71eab.
