### ISSUE TITLE
@field comments not rendering after 1.4.2

### ISSUE THREAD

**Issue by develephant** [lunarmodules/ldoc#202]
After version 1.4.2, any field comments don't seem to be rendering.

--- My Table
-- @string my_param This text here is not rendering after 1.4.2
-- @table my_table

Best.

**Comment by stevedonovan** [comment]
Sorry I'm so late in replying. I'm not seeing the problem here - looking at the tests/styles/opt.lua example, the table renders as expected.

**Comment by alerque** [comment]
This seems to be working too. Happy to re-evaluate if you have a working test case a current problem.
