### ISSUE TITLE
Optionally return non-zero in case of doc issues

### ISSUE THREAD

**Issue by blueyed** [lunarmodules/ldoc#213]
It would be useful if `ldoc` could exit with a non-zero return code in case of errors like `param and formal argument name mismatch`.

This could be used in CI builds to make sure the documentation is correct.

**Comment by stevedonovan** [comment]
`--fatalwarnings` already existed for exactly this purpose, but it didn't cover parser errors. So this fix should be about right now.

**Comment by alerque** [comment]
Fixed in ebdbf7d.
