### ISSUE TITLE
fix moonscript constructor auto-assignment parameters

### ISSUE THREAD

**Issue by s-ol** [lunarmodules/LDoc#229]
moonscript has auto-assign parameters that start with an `@`:

``` moon
class Toast
  new: (@a, @b=3) =>

toast = Toast 2, 5
print toast.a, toast.b -- => 2, 5
```

Ldoc parses the parameters as just `@`
## 

also fat arrow methods and `self` aren't properly handled, they show up as seperate arguments and without the colon.

**Comment by stevedonovan** [comment]
This should be better - commit dadad3f73716

**Comment by s-ol** [comment]
Hey! Moonscript support got a lot better, thanks. I'm having some more issues where I'm not sure whether they are bugs, questions of feature requests, so I'll piggy-back on this issue for a second if you don't mind @stevedonovan:

- It seems that right now all functions in classes become methods (using `Class\\method` syntax). However I also often add static functions (using `->`). ldoc doesn't seem to detect this. Is there a way I can declare a function as "static", so that it is shows as `Class.method`?
- using `@classmod`, I can document refer to classes using `@{Class}`, but I can't seem to refer to any methods. I've tried: `Class.method`, `Class:method`, `Class\\method`, the same with parenthesis etc, but it's never a valid reference.
- It is valid moonscript to define class members with an `@name`, which assigns them to the class itself rather than to the `__index` table:

```
class Test
  @static: -> print "hello"
```

This currently fails parsing by ldoc causes internal errors.

**Comment by s-ol** [comment]
Thinking about it some more, here's how *I think* it should work:

- `->` vs `=>` decides whether a `abc.def` or `abc\def` is used
- `name:` vs `@name` decides whether `Class` or `instance` is used

so that

```
class Test
  method: =>
  func: ->

  @static_func: ->
  @static_method: =>
```
gets shown in ldoc as `test\method ()`, `test.func ()`, `Test.static_func ()` and `Test\static_method ()`. Static methods might seem odd from OOP perspective, but are actually quite useful.

**Comment by alerque** [comment]
Hey @sol what's the status on this for you? If there is something to fix I'll be happy to review PRs, but as far as Moonscript support you'll probably have to write the PR yourself ;-) I'm not sure what to do with this as is. The original issue seems solved, no? Should we close it or are we still tracking these other thoughts as something actionable?

**Comment by s-ol** [comment]
Hey, I did essntially what I proposed above in a fork: https://github.com/s-ol/LDoc/commit/cdd859da4b86e3603e0236b25fb145a28b8c2cb9

You can see what it does here: [source](https://github.com/s-ol/alive/blob/master/alv/base/op.moon) - [output](https://alv.s-ol.nu/stable/internals/classes/Op.html)

If you want to have this behaviour, maybe behind a flag, I'm happy to send a PR. In the meantime we can close this issue.

**Comment by alerque** [comment]
Thanks for the background, this is slowly starting to make sense.

Yes I think I would like to see that PR'ed. I looked at opening a PR myself from your moonscript branch but because you also have the rockspec modified I think preparing this there might disrupt your current usage. Maybe cherry picking that into another branch to PR from would be better.

I also see you applied what looks like #273 to your moonscript branch. Perhaps with your feedback on that PR we can get that merged too!
