### ISSUE TITLE
LDoc 1.4.4 roadmap

### ISSUE THREAD

**Issue by stevedonovan** [lunarmodules/LDoc#242]
Planning on doing a pre-release candidate this weekend, and I'm wondering what _new_ features we need to start thinking about:
- The feeling is that the default look-and-feel is still early 21st C and needs an update. In particular, it's common for people to want to browse API documentation on mobile devices.
- Would be useful to have a gallery of styles/templates. Anybody who has made LDoc output pretty is welcome to suggest themes which can be made available
- Options other than wholesale CSS replacement - we now have the ability to add extra CSS (see https://github.com/stevedonovan/LDoc/pull/223) but I'm wondering if CSS templates are worth implementing. These are expanded as needed, and can be controlled by a dozen or so widths and colours.
-  I have an itch to prettify the output of `ldoc -m` on terminals that understand ANSI colour sequences. Any thoughts?
- regression testing is now possible due to `--testing` flag, but the test coverage needs to be greatly expanded  

Fixing and closing existing issues is the big priority now but I wanted to know how users feel about the future of this project.

**Comment by Fuzzlix** [comment]
I am very interested in this project. i tried using it some time ago - i tried using it last week, and again i stepped back to pure markdown and hand made css.  
ldoc ignores things without createing errors/warnings and i have to spend a lot of time for try and error loops to get a nice output. for instance:

``` Lua
--- something i want do write.
-- bla blub
-- blubber
-- @section somemodules
package.preload["mymod"] = function(...)
  local xyz;
  --- something to document.
  -- blablabber
  function xyz()
  end;
end;
```
Result: the section somemodules does not show up in the html, function xyz does not show up in the html and for shure it does not show up in section somemodules.   
As often i tried to use ldoc i ended up fighting with the internal and unknown ldoc logic. Ldoc may work well with standard lua sources but as soon the source is oop-style and/or includes preloaded modules, ldoc fails. If you ask me what i whish, i would answer: KISS!  
Why a @within keyword? Simply use @section instead. If a section does not exist, create it, if it exist append to the existing section.  
Why ckecking local/global? this check does not work anyway. `local x;` x is detected as local. `local x; x=something;` x is detected as global.
Thats only 2 things coming in my mind 2 days after moving back to mmd. I simply dont want to spend 2 weeks in try and error runs without the feeling i will be able to end up sucessfully.

best wishes.
Ulrich.

**Comment by stevedonovan** [comment]
Actually, your example works fine if we give the item a name:

```lua
--- something i want do write.
-- bla blub
-- blubber
-- @function mymod
-- @within somemodules
package.preload["mymod"] = function(...)
  local xyz;
  --- something to document.
  -- blablabber
  function xyz()
  end;
end;
```
There's no way that LDoc could parse _every_ way of expressing something in Lua, so sometimes you just have to give the dog a name.  As for **@within** here, it says that this function must be inside a section, which will be created if needed.  **@section* is a way of grouping items. So they approach the same concept from different angles.

But I get your point about warnings; in this case a reasonable tool is expected to say something like "I can't understand your code! Use explicit type/name!". I'll definitely add that to the list.

KISS is a fantastic concept but our problem here is that Lua - despite being a beautifully simple language - allows so much flexibility in defining constructs like classes and functions.

**Comment by stevedonovan** [comment]
Ulrich, but thanks for focusing my attention on the _basics_; I too dislike tools that fail silently. And also, documentation tools cannot have too much documentation.

**Comment by Fuzzlix** [comment]
> KISS is a fantastic concept but our problem here is that Lua - despite being a beautifully simple language - allows so much flexibility in defining constructs like classes and functions.

Exactly! Correct me if i am wrong. It looks to me, ldoc try to interpret my source code. This try will fail in many cases. In case of my example "mymod" is no function - it is a self standing module.
You already implemented @function, @type, @table to override ldoc's interpretation. Fine! But i miss such a tag for simple variables (@var, @tvar). For OOP i miss methods(@method) and properties(@prop, @tprop). Also @class and @object( = @tvar object) tags would be better than a simple @type tag.
I know, this is my personal view only. May be most of your users are satisfied already.

**Comment by stevedonovan** [comment]
Yeah, it's a pity that **@class** was already used by LuaDoc, and I've tried to be compatible.  Usually **@function** and **@field** does the work of **@method** and **@prop** although they aren't quite the same! In particular, whether a method is 'static' or not to use the awful C++ terms.

With your method, a file may contain multiple modules - already possible, but it would be hard to force the idea of multiple modules into LDoc's head without headaches.

**Comment by Fuzzlix** [comment]
I agree. So lets talk about compatibilty with "xy". When i want to use a documentation tool, i want to use THIS ONE tool because its abilities and i dont use a other tool at the same time for the same project. So compatibility is no primary goal for me - may be for others who want to continue a existing project using ldoc.
I cant tell you what is the best way to do for you, i can tell you only my point of view. That is: I would define a usefull and complete as possible tag set and tag syntax. It should be open for later additions. The tag syntax is ok, when i can write a source without any code lines (pure ldoc comments) and ldoc creates a documentation as expected. In addition ldoc can use code lines following a ldoc comment as additional source of information. When ldoc sticks too close on a source code, it suffers limitations in usefullness and universality.
But as i said, its my two cents only.

**Comment by mpeterv** [comment]
It would be nice to have support for modules that are not a table or a class but a single function. E.g.

```lua
-- Some imports and local helper functions go here

return function(a, b, c)
   -- ...
end
```

**Comment by stevedonovan** [comment]
I was about to say that we do support this syntax, but I see what you mean: such a 'module' exports a single unnamed function - it does not _contain_ a single function.  Someone should be able to look at the docs and say, 'OK, local f = require 'funmod' will return a function'.

Just pushed ff60cbd7a which fixes the existing broken implementation

**Comment by houqp** [comment]
+1 to the new default theme ;)
