### ISSUE TITLE
luaposix LDocs generation worked with 1.4.4 but crashes with latest luarocks releases

### ISSUE THREAD

**Issue by gvvaughan** [lunarmodules/LDoc#251]
I received pull-request https://github.com/luaposix/luaposix/pull/253 a couple of days ago, but it failed regression tests in Travis because recent luarocks LDocs crash when parsing the `@section table` comment near the end of `ext/posix/fcntl.c` (until I removed it and reordered the file contents in the latest commit to work around the bug).

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       ext/posix/posix.lo
  CCLD     ext/posix/posix.la
test -d ./doc || mkdir ./doc
/usr/local/bin/ldoc -c build-aux/config.ld -d /Users/gary/Desktop/Dropbox/Projects/luaposix--git--0/doc .
reading configuration from build-aux/config.ld
changing to directory   build-aux
found master module /Users/gary/Desktop/Dropbox/projects/luaposix--git--0/lib/posix/init.lua
/Users/gary/Desktop/Dropbox/projects/luaposix--git--0/ext/posix/fcntl.c:281: internal LDoc error
/usr/local/share/lua/5.2/ldoc/tools.lua:112: table index is nil
stack traceback:
    /usr/local/share/lua/5.2/ldoc/tools.lua:112: in function 'add'
    /usr/local/share/lua/5.2/ldoc/doc.lua:397: in function 'finish'
    /usr/local/share/lua/5.2/ldoc/parse.lua:424: in function </usr/local/share/lua/5.2/ldoc/parse.lua:424>
    [C]: in function 'xpcall'
    /usr/local/share/lua/5.2/ldoc/parse.lua:424: in function 'file'
    /usr/local/lib/luarocks/rocks-5.2/ldoc/1.4.5-1/bin/ldoc:414: in function 'process_file'
    /usr/local/lib/luarocks/rocks-5.2/ldoc/1.4.5-1/bin/ldoc:469: in function 'process_all_files'
    /usr/local/lib/luarocks/rocks-5.2/ldoc/1.4.5-1/bin/ldoc:476: in main chunk
    [C]: in ?
make[1]: *** [doc/index.html] Error 255
make: *** [all] Error 2
```

Bisecting shows the regression was introduced in commit 3dada49e, and some experimentation shows that the following patch restores the old behaviour:

``` diff
diff --git a/ldoc/doc.lua b/ldoc/doc.lua                                                                   
index 05474e8..56db4b0 100644                                                                              
--- a/ldoc/doc.lua                                                                                         
+++ b/ldoc/doc.lua                                                                                         
@@ -294,7 +294,7 @@ function File:finish()                                                                 
             end                                                                                           
             item.display_name = display_name                                                              
             this_mod.section = item                                                                       
-            this_mod.kinds:add_kind(display_name,display_name,nil,item)                                   
+            this_mod.kinds:add_kind(display_name,display_name..' ',nil,item)                              
             this_mod.sections:append(item)                                                                
             this_mod.sections.by_name[lookup_name:gsub('%A','_')] = item                                  
          end                                                                                              
```

I don't understand the internals of LDocs well enough to find the root cause here.  Perhaps the additional space is a valid key into the table of sections made elsewhere, and without it trying to use `@section tables` (specifically the `Tables.` comment from the immediately preceding line) cannot find the right section somehow?

**Comment by stevedonovan** [comment]
Ok, time to fix Ldoc ;)  I've been breaking the build of Awesome recently so it's time to tame some of the hacks that have crept in - like that extra space.

**Comment by stevedonovan** [comment]
OK, the problem I have is that your master's docs don't break with my ldoc master ;)

I am still trying to understand why that little, irritating space is needed, and a breaking example would be most appreciated.

**Comment by gvvaughan** [comment]
Hi Steve,

Thanks for investigating! To reproduce you'll need luaposix checked out at hashref 3ab67b5, just before I introduced the workaround.

The input that causes the problem is having this near the end of a file:

```c
/*
Tables.
@section tables
*/
```

The other sources in luaposix don't change the ldoc section explicitly before any `@table` docs, but `ext/posix/fcntl.c` also has an explicit `@section constants` which I need to switch out of so that the following `@table` doesn't ent up in the Constants section.

The workaround I used was to remove the Tables comment quoted above entirely, and the move te rest of the table documentation from the end of the ike to the beginning.

HTH! Gary

**Comment by stevedonovan** [comment]
Cool, I'll do just that...

**Comment by stevedonovan** [comment]
It's a simple problem, but I'm wondering about the best solution. The section is 'Tables' which is one of the predefined section types. So one option is to detect this case and fall back to the default behaviour - tables will be naturally collected in the Tables section.  (That extra ..' ' is now understood - forces update of the kind maps. But..yuk)

**Comment by gvvaughan** [comment]
Do you mean that all `@table` declarations would be collected into the predefined Tables section? While that would solve the specific problem I tickled in luaposix fcntl.c, I think it would be "surprising" behavior for an `@table` in the custom Constants section to show up in a different section than it did in 1.4.4 generated docs - which would likely be a problem with other luaposix LDocs.

From my perspective as a user, if putting that space back restores the previous behavior, that would be a fine fix! :-)

**Comment by stevedonovan** [comment]
You're right! At least now, I've _commented_ why that damn space is in there ;)
