### ISSUE TITLE
Can't make markdown and plain output

### ISSUE THREAD

**Issue by sjahn90** [lunarmodules/LDoc#256]
I tried markdown or plain format. But I can't make the formats. Everytime, output format is html.
ldoc version is 1.4.6.
$ldoc -f 'discount' test.lua or ldoc -f 'plain' test.lua
output format is html..

How can I make markdown and plain format using ldoc ?

**Comment by beadsland** [comment]
Seeing same issue with ldoc version 1.4.6-2. Option -f is ignored on command line. 'format' setting is ignored in config.ld. Output is consistently HTML regardless of what alternative is specified.

**Comment by ldurniat** [comment]
@sjahn90 @beadsland : 

From github [documentation](https://github.com/stevedonovan/LDoc/blob/master/doc/doc.md#generating-html):

> Of course, there's no reason why LDoc must always generate HTML. --ext defines what output extension to use; this can also be set in the configuration file. So it's possible to write a template that converts LDoc output to LaTex, for instance. The separation of processing and presentation makes this kind of new application possible with LDoc.
> 
> From 1.4, LDoc has some limited support for generating Markdown output, although only for single files currently. Use --ext md for this. 'ldoc/html/ldoc_md_ltp.lua' defines the template for Markdown, but this can be overriden with template as above. It's another example of minimal structure, and provides a better place to learn about these templates than the rather elaborate default HTML template.

From github.io [documentation](https://stevedonovan.github.io/ldoc/):

> ldoc, a documentation generator for Lua, vs 1.4.3
>   ...
>   -f,--format (default plain) formatting - can be markdown, discount or plain
>   ...
> 

So the `-f` or `--format` indicate format of source file(s). To change output format use `--ext extension`.

I built only html doc so I'm not sure 100% it works.

Have a nice day:)
ldurniat

**Comment by Perlovka** [comment]
ldoc-1.4.6 failed to build markdown output

`ldoc -x md`

 failed with:
```
template failed for test: [string "TMP"]:49: attempt to call global 'no_spaces' (a nil value)
stack traceback:
	[string "TMP"]:49: in function 'fn'
	/usr/share/lua/5.1/pl/template.lua:91: in function </usr/share/lua/5.1/pl/template.lua:91>
	[C]: in function 'xpcall'
	/usr/share/lua/5.1/pl/template.lua:91: in function 'substitute'
	/usr/share/lua/5.1/ldoc/html.lua:283: in function 'templatize'
	/usr/share/lua/5.1/ldoc/html.lua:320: in function 'generate_output'
	/usr/share/lua/5.1/ldoc.lua:830: in main chunk
	[C]: ?
```

**Comment by Perlovka** [comment]
Actually, with latest penlight (1.5.4) output slightly changed:
```
template failed for test: [string "TMP"]:64: attempt to call global 'no_spaces' (a nil value)
stack traceback:
	[string "TMP"]:64: in function <[string "TMP"]:1>
	[C]: in function 'xpcall'
	/usr/share/lua/5.1/pl/template.lua:138: in function </usr/share/lua/5.1/pl/template.lua:131>
	(tail call): ?
	/usr/share/lua/5.1/ldoc/html.lua:283: in function 'templatize'
	/usr/share/lua/5.1/ldoc/html.lua:320: in function 'generate_output'
	/usr/share/lua/5.1/ldoc.lua:830: in main chunk
	[C]: ?
```

**Comment by norcalli** [comment]
I'm getting exactly the same error.

**Comment by davporte** [comment]
Same here:

	[string "TMP"]:64: in function <[string "TMP"]:1>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.3/pl/template.lua:140: in function </usr/local/share/lua/5.3/pl/template.lua:133>
	(...tail calls...)
	/Users/davporte/Desktop/LDoc-master/ldoc/html.lua:283: in local 'templatize'
	/Users/davporte/Desktop/LDoc-master/ldoc/html.lua:320: in function 'ldoc.html.generate_output'
	/Users/davporte/Desktop/LDoc-master/ldoc.lua:830: in main chunk
	[C]: in ?

**Comment by Perlovka** [comment]
ldoc.lua:
```lua
   if ldoc.template == '!' then
      ldoc.template = '!md'
   end
```
should be
```lua
   if not ldoc.template or ldoc.template == '!' then
      ldoc.template = '!md'
   end
```

**Comment by etc0de** [comment]
Would it somehow be possible to get this fix merged?
