### ISSUE TITLE
Dependency issue with regard to penlight

### ISSUE THREAD

**Issue by AlexandreRio** [lunarmodules/LDoc#268]
Hi, I just noticed that with ldoc 1.4.6-2 (from luarocks) I had a bug with penlight (which was in version 1.4.0-1) the error was very misleading (nil concatenation error).
I solved it by upgrading to 1.5.0-1, still got the error and finally to 1.5.2-1 which solved it.

Why don't you use version requirement in the rockspec file?

**Comment by stevedonovan** [comment]
Good question, and yes I will do this. Sorry about the 1.5.0 instability - was released too fast.
