### ISSUE TITLE
Are there any IDEs with lDoc support?

### ISSUE THREAD

**Issue by ghost** [lunarmodules/LDoc#295]
It would be nice if there was at least one IDE that can show hints and offer autocomplete based on lDoc.

**Comment by Winterwolf** [comment]
It would be nice if there was at least one IDE that can show hints and offer autocomplete to functions based on lDoc.

**Comment by tuxd3v** [comment]
good question..

**Comment by alerque** [comment]
Fair question, but I don't know of any. Feel free to request it as a feature request on your favorite IDE's project, but I don't think this project itself should be responsible for making that happen.
