### ISSUE TITLE
[SOLVED] Using 'string.split' in config.ld

### ISSUE THREAD

**Issue by AntumDeluge** [lunarmodules/LDoc#304]
I want to use the *string* function *string.split* in my *config.ld*. But I can't seem to import it:

```
error loading config file config.ld: [string "config"]:1: attempt to call global 'require' (a nil value)
```

Is there a way to import the module?

**Comment by AntumDeluge** [comment]
I figured out how to use the ***require*** command by modifying & adding the following line to the source:

*ldoc.lua:*
```lua
-- Enable using `require` command from within `config.ld`
ldoc.require = require
```

To import the ***string*** module, I can now call `require "string"` from within `config.ld`, or just set it as an `ldoc` object as well in the source:

*ldoc.lua:*
```lua
-- Enable `string` module within `config.ld`
ldoc.string = require "string"
```

However, the `string` module that comes with LDoc doesn't seem to have a `string.split` function. So I guess I will have to write one.

**Comment by alerque** [comment]
See my comments in #308.
