### ISSUE TITLE
[SOLVED] Using Multiple "module" in Single File

### ISSUE THREAD

**Issue by AntumDeluge** [lunarmodules/LDoc#305]
I'm putting all documentation into a separate file. Is it possible to use the `@module/@script/@file` tags multiple times in a single file? Something like `@section end` would be nice.

**SOLVED:** By commenting out the following lines in `ldoc/parse.lua` I was able to achieve the behavior that I wanted:
```
if module_item then
  F:error("Module already declared!")
end
```
Going to leave this open for now in case someone finds it helpful.

**Comment by esrrhs** [comment]
@AntumDeluge I had same problem, and I also comment the F:error
