### ISSUE TITLE
Optionnal args to functions, and refs to Lua Ref Manual

### ISSUE THREAD

**Issue by Yonaba** [lunarmodules/ldoc#31]
First of all, let me say that this is _indeed_ a very handy tool.
I am using LDoc to generate documentation for a utility-belt library of mine, [Moses](http://github.com/Yonaba/Moses).

I have some suggestions, though. Would it be possible to add support for optional args to a function ? I would love to have a syntax like this in the generated docs:

``` lua
function foo(a, b [,c])
```

Besides this, I am using a standard version of LDoc, wihtout any custom changes. I just customised the <tt>config.ld</tt> file. I noticed that HTML references to the Lua Ref Manual are automatically added for string and table types. How can I add my custom ones ? For functions, numbers, and so on ?

Thanks in advance

**Comment by alerque** [comment]
This seems to have been addressed already.
