### ISSUE TITLE
[bug] Custom types don't work

### ISSUE THREAD

**Issue by Jummit** [lunarmodules/LDoc#310]
Putting `new_type("custom", "Custom")` in the `config.ld` and the putting something like this
```lua
----
-- This is a test
-- @custom test
```
in the project gives the error `test.lua:4: ?: 'class' cannot have multiple values; {custom,module}`:
Is this supposed to happen an I am missing something?

**Comment by AntumDeluge** [comment]
I believe your file needs to start with a "module", "class", or "script" section:
```lua
--- A module.
-- @module test.lua

---
-- This is a test
-- @custom test
```
