### ISSUE TITLE
LDoc is not generating anything

### ISSUE THREAD

**Issue by ktalebian** [lunarmodules/LDoc#313]
I used the example from the documentation page:

```lua
--- another test.
-- @module test2
-- @alias M

local M = {}

-- first test.
function M.one()

end

return M
```

and then generated the doc using: 

```bash
➜ lua ~/Downloads/LDoc-master/ldoc.lua -a test.lua
output written to ~/project/doc
```

But the output of the doc only has the `@module` information:

![image](https://user-images.githubusercontent.com/2308915/53524263-cb7bc300-3a93-11e9-93ac-07391b8daf6e.png)

**Comment by etc0de** [comment]
Only functions with a doc comment are listed, so if you use `--- first test` (three dashes, to indicate it's a doc comment) it should work.
