### ISSUE TITLE
format: markdown not found, falling back to text

### ISSUE THREAD

**Issue by adrfantini** [lunarmodules/LDoc#328]
I can't understand how to process a documentation with Markdown.

If I set `format = 'markdown'` I get:
```
format: markdown not found, falling back to text
```

If I set `format = 'lunamark'` I get:
```
format: lunamark not found, falling back to text
```

If I set `format = 'discount'` I get:
```
format: discount not found, falling back to text
```

Both `lunamark` and `discount` are installed and can be loaded from Lua5.3. OS is Kubuntu 20.04.

What am I doing wrong?

**Comment by adrfantini** [comment]
I might have found two possible reasons for the above issue.
One is this bugreport:
https://bugs.launchpad.net/ubuntu/+source/lua-ldoc/+bug/1868550

which says that `markdown.lua` might be missing. Applying the suggested fix does fix the problem, if I do it for Lua5.2, and not 5.3.

This brings me to the other possible problem, which is that `ldoc` is using Lua5.2. The package explicitly says it supports Lua5.3, but if my default `lua` executable is 5.3, then I get:
```
> ldoc --help
Error: no suitable Lua interpreter found
Error: supported versions are: 5.2 5.1
```

Thus, packages that I install with e.g. luaRocks for 5.3 appear to not be available to `ldoc`, since it uses 5.2 and cannot use 5.3.

**Comment by idbrii** [comment]
How did you install lua, luarocks, and ldoc?

I installed like this on Ubuntu 20.04.1 LTS:
```
sudo apt-get install lua5.3 liblua5.3-dev luarocks
luarocks --local install https://raw.githubusercontent.com/lunarmodules/LDoc/master/ldoc-scm-3.rockspec
```

and had no problems using markdown.

(The version of ldoc on luarocks is quite old -- from 2016.)

**Comment by adrfantini** [comment]
With the latest ldoc I do not have this problem anymore on (K)Ubuntu 20.04.2 LTS.
