### ISSUE TITLE
C method call with `:`?

### ISSUE THREAD

**Issue by Hibou57** [lunarmodules/ldoc#330]
https://github.com/stevedonovan/LDoc/blob/f91c3182cf0b3ac29a8f677491aa32493067b5e1/ldoc/lang.lua#L256

It says:

    function CC:_init()
       self.line_comment = '^//+'
       self.start_comment_ = '^///+'
       self.block_comment = '^/%*%*+'
       self.method_call = ':'
       self:finalize()
    end

Unless I missed something, I feel this should be `self.method_call = '.'` or may be `'->'`

**Comment by alerque** [comment]
You'd be right if this was for C method calls, but see a few lines up from that:

> -- Note: this applies to C/C++ code used to generate _Lua_ documentation!

This function is for parsing C comments, but the documentation being generated is for Lua usage.
