### ISSUE TITLE
Cannot use string methods in custom_display_name_handler

### ISSUE THREAD

**Issue by lua-rocks** [lunarmodules/LDoc#350]
Why did you remove `_G` from `config.ld`? I need to parse `item.name` but `string.sub()` is not available.

I am lucky that I only need a string and this issue can be worked around like this: `item.name:sub()`. But if I needed to process a table with `table` methods or do some `math`, then that would be a problem.

**Comment by Elv13** [comment]
See https://github.com/lunarmodules/LDoc/issues/333 and https://github.com/lunarmodules/LDoc/issues/308

If you are desperate and still want to use a non-forked ldoc, know that the template code sandbox is "buggy" and let you get a reference to the penlight and normal modules. See our horribly unmaintainable doc here

https://github.com/awesomeWM/awesome/blob/master/docs/config.ld
https://github.com/awesomeWM/awesome/blob/master/docs/ldoc.ltp
https://awesomewm.org/apidoc/core_components/tag.html

In my humble opinion, the ldoc config.ld sandbox is counter intuitive and should be optionally disabled. It prevents you from adding extensions to ldoc, which, once disabled, just works.

**Comment by lua-rocks** [comment]
@Elv13 Thank you for the answer! Can you please advise me a good fork? I don't know anything about them.

**Comment by Elv13** [comment]
> Can you please advise me a good fork? I don't know anything about them.

I don't think there is a "better" fork. It depends on your use case. For AwesomeWM, I just monkey-patched the template to get rid of some restrictions. However this is because I *didn't* want to fork. Forking would make some Linux distribution unhappy, so it isn't an option for me. But if you don't care, copy paste the codebase into your project and do whatever you need to get the features you need.

**Comment by alerque** [comment]
The comments here about string functions are not correct, they can be accessed using methods. See https://github.com/lunarmodules/ldoc/issues/203#issuecomment-228612604
