### ISSUE TITLE
Documentation Links are Wrong

### ISSUE THREAD

**Issue by AntumDeluge** [lunarmodules/LDoc#354]
A few hyperlinks are pointing to invalid URLs:

- The link on the GitHub main page points to http://stevedonovan.github.com/ldoc/ when it should be http://stevedonovan.github.io/ldoc/
- In README.md:
  - Penlight link points to http://lunarmodules.github.com/Penlight/api/index.html when it should be http://lunarmodules.github.io/Penlight/
  - Winapi link points to http://stevedonovan.github.com/winapi/api.html when it should be http://stevedonovan.github.io/winapi/api.html
  - LuaFileSystem link points to http://keplerproject.github.com/luafilesystem/ when it should be http://keplerproject.github.io/luafilesystem/

**Comment by catwell** [comment]
Fixed, thanks.

I have also added `https://` where it worked and removed the links to rendered examples in `doc.md` (they no longer exist, we should host those on lunarmodules itself someday).
