### ISSUE TITLE
Colon tag troubles, some comment stuff

### ISSUE THREAD

**Issue by ggcrunchy** [lunarmodules/ldoc#37]
Hi.

On updating, a few things seemed to blow up on me with colons (having updated to try out the colon syntax :smile:).

In a case like

https://github.com/ggcrunchy/corona-sdk-snippets/blob/master/dot/Warp.lua#L159

everything is okay, but

https://github.com/ggcrunchy/corona-sdk-snippets/blob/master/dot/Warp.lua#L204

complains with something like "unknown tag: method nil". Cases of the former have "@" tags, and the rest don't, so I'm guessing that gets "method:" disambiguated (on purpose?).

This is showing up with file summaries, too.

Is this expected behavior? I had thought tags only showed up on the first word, apart from special forms like "@{STUFF}". Anyhow, liberal sprinkling of "&# 58;", for now...

Less bothersome, but in case these matter, the update flagged these down:

An otherwise-empty "---" and "----------------------" both error out. If the first case is the file summary, the error seems to misdirect you to a lower line. One instance of "---" was within a long comment too; not sure if that's expected.

**Comment by alerque** [comment]
As far as I can tell from skim reading this issue has long-since been addressed. Feel free to comment if I missed something and there is still an outstanding problem.
