### ISSUE TITLE
Using custom CSS (-s option) fails with error: ldoc/tools.lua:233: attempt to compare number with nil

### ISSUE THREAD

**Issue by adrfantini** [lunarmodules/LDoc#373]
As per title, using the `-s` option for using a custom CSS fails with the following error:  
```
/usr/bin/lua5.3: /usr/local/share/lua/5.3/ldoc/tools.lua:233: attempt to compare number with nil
stack traceback:
        /usr/local/share/lua/5.3/ldoc/tools.lua:233: in function 'ldoc.tools.check_file'
        /usr/local/share/lua/5.3/ldoc/html.lua:341: in function 'ldoc.html.generate_output'
        /usr/local/lib/luarocks/rocks-5.3/ldoc/scm-3/bin/ldoc:849: in main chunk
        [C]: in ?
```

How to reproduce on ldoc v1.4.6:
1. Create a sample lua file (e.g. `lua.lua`) with documentation tags
2. Run `ldoc lua.lua`: everything is fine
3. Run `ldoc -s doc/ldoc.css lua.lua` to manually include ldoc's own CSS, created in the previous step
4. See the above error message

**Comment by alerque** [comment]
The `-s` argument is not looking for a file, it is looking for a **directory**:

> -s,--style          (default !) directory for style sheet (ldoc.css)

It assumes it will find a file called `ldoc.css` in the given directory, so for your example you need to use `ldoc -s doc lua.lua`

We could add a check that errors with a more sensible message before getting so deep into trouble.

**Comment by adrfantini** [comment]
Whoops! Sorry about that
