### ISSUE TITLE
How to use @script tag?

### ISSUE THREAD

**Issue by leaveye** [lunarmodules/LDoc#386]
I have failed in these ways:

```lua
---
-- aka:
--@script
-- function()
--   call(1)
-- end
function foo() ... end
```

```lua
---
-- aka:
--@script function()
--@script   call(1)
--@script end
function foo() ... end
```

```lua
---
-- aka:
--@script aka
-- function()
--   call(1)
-- end
--@script aka
function foo() ... end
```

**Comment by Tieske** [comment]
the `@script` tag (without any parameters) is used at the module level to indicate this file contains a CLI script, and not a code module.

Your examples seem to indicate you'd like to provide example use. For that use the `@usage` tag.

```lua
--- some function. Will do something.
-- @tparam string p1 the name to pass along
-- @return true on success
-- @usage
-- local p1 = "hello world"
-- local result = do_something(p1)
local function do_something(p1)
  -- do something with the p1 value
  return true
end
```

**Comment by alerque** [comment]
If that doesn't answer your question @leaveye please do comment back here and I'll re-open, but to my eyes this looks like it probably answers your question so I'm going to mark it as closed.
