### ISSUE TITLE
multiple raise statements cause error

### ISSUE THREAD

**Issue by mb6ockatf** [lunarmodules/ldoc#400]
hello. got that while trying to generate docs:
```bash
template failed for mfr: /usr/local/share/lua/5.4/ldoc/markup.lua:313: attempt to call a nil value (method 'gsub')
stack traceback:
        /usr/local/share/lua/5.4/ldoc/markup.lua:313: in function 'ldoc.markup.processor'
        (...tail calls...)
        [string "TMP"]:481: in function <[string "TMP"]:1>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.4/pl/template.lua:140: in function </usr/local/share/lua/5.4/pl/template.lua:133>
        (...tail calls...)
        /usr/local/share/lua/5.4/ldoc/html.lua:283: in local 'templatize'
        /usr/local/share/lua/5.4/ldoc/html.lua:320: in function 'ldoc.html.generate_output'
        /usr/local/lib/luarocks/rocks-5.4/ldoc/1.5.0-1/bin/ldoc:898: in main chunk
        [C]: in ?
```

note, that in line 312 of /usr/local/share/lua/5.4/ldoc/markup.lua:313, there is such a comment:
```lua
-- hack to separate paragraphs with blank lines
```

my `config.ld` contents are:
```lua
title = "stuff"
project = "stuff"
not_luadoc = true
boilerplate = false
file = {"stuff.lua"}
```
how do i fix it? what could have gone the wrong way?

thanks to one who reply

**Comment by alerque** [comment]
I think we'll probably need to see your *input*. Do you have a sample of Lua code your are trying to generate docs for that shows this error?

**Comment by mb6ockatf** [comment]
> I think we'll probably need to see your _input_. Do you have a sample of Lua code your are trying to generate docs for that shows this error?

i have writeen += 300 lines of code & docstrings since i last generated docs. the following example also fails with the same error
```lua
#!/usr/bin/env lua

---@module mfr

mfr = {}

--- create line borders.
-- note that all tabs will be converted to character sequence defined by
-- `set_tab_representation` - 4 spaces is a default value.
-- please, note that border param is cut, and only its 1st symbol is used.
-- @tparam string text text to be displayed put inside borders
-- @tparam number length length of the frame
-- @tparam string border border to put text into
-- @treturn string bordered text
-- @raise if text is not a string
-- @raise if length is not a number
-- @raise if border is not a string
-- @see mfr.set_tab_representation
-- @see mfr.create_frame
-- @see mfr.create_page_borders
function mfr.create_line_borders(text, length, border)
	if type(text) == "table" and not length then
		border, length = text.border, text.length
		text = text.text
	end
	length, border = length or 80, border or "*"
	border = border:sub(1)
	assert(type(text) == "string", "text is string")
	assert(type(length) == "number", "length is number")
	assert(type(border) == "string", "pattern is string")
	assert(length > 4, "length is larger than 4")
	text = text:gsub("\t", mfr._TAB_REPRESENTATION)
	assert(length - text:len() > 4, "text is shorter than length by 4")
	local spacing = string.rep(" ", length - 3 - text:len())
	return border .. " " .. text .. spacing .. border .. "\n"
end

return mfr
```

there are errors for invalid `@see` statements, but i do not think they're the reason

**Comment by alerque** [comment]
The goal is a *minimum* example. This for example:

```lua
#!/usr/bin/env lua

---@module mfr

mfr = {}

--- create line borders
-- @raise if length is not a number
-- @raise if border is not a string
function mfr.create_line_borders(text, length, border)
end

return mfr
```

**Comment by mb6ockatf** [comment]
> The goal is a _minimum_ example. This for example:
> 
> ```lua
> #!/usr/bin/env lua
> 
> ---@module mfr
> 
> mfr = {}
> 
> --- create line borders
> -- @raise if length is not a number
> -- @raise if border is not a string
> function mfr.create_line_borders(text, length, border)
> end
> 
> return mfr
> ```

oh, i see. ldoc doesn't like multiple `raise` statements, and it works fine if i remove the 2nd one. thank you

**Comment by mb6ockatf** [comment]
i've renamed the issue, so it is easier to search for in case someone like myself will struggle with the same error.

neither documentation, not README.md says anything about `ldoc` not liking multiple `raise` lines. this issue is closed as *won't fix*

**Comment by mb6ockatf** [comment]
by the way, having many `see` & `tparam` lines works fine
