### ISSUE TITLE
parameter description indention

### ISSUE THREAD

**Issue by ToadJamb** [lunarmodules/ldoc#43]
I would like to be able to format parameter comments along the lines of:

``` lua
--- A function that does really useful stuff.
-- string: text         This parameter accepts a string.
--                      More information that gets appended to the first line.
-- number: magic_number This parameter accepts a number.
--
--                      More information (on a new line) about `magic_number`.
function (text, magic_number)
  ...
end
```

There are two issues that I see when I try this:
1. The comment for the text parameter ends up in a code block (as it is 'indented' more than four spaces).
2. Any of the additional information lines end up in a code block since they are indented more than four spaces.

I guess this raises two questions for me.

Is this the desired behavior? Do people really put code blocks in parameter descriptions? (I can't recall a single time that I have).

**Comment by alerque** [comment]
Long since fixed.
