### ISSUE TITLE
Allow @{mynamespace.function} reference inside code examples

### ISSUE THREAD

**Issue by ghost** [lunarmodules/ldoc#55]
I apologize if this is already possible, but the way I tried it didn't work:

``` c
// @usage -- play sound file "blubber.ogg" at 80% volume and
// -- fade in for 5 seconds
// mysound2 = @{blitwizard.audio.simpleSound:new}("blubber.ogg")
// mysound2:play(0.8, 8)
```

My expectation was that the function name would become clickable so that the user can instantly jump to that particular function by clicking its name inside the example code. However, I end up with `@{blitwizard.audio.simpleSound:new}` literally appearing inside the example code.

**Comment by alerque** [comment]
This should be addressed, if anything is still missing feel free to comment for re-evaluation.
