### ISSUE TITLE
sorting contents

### ISSUE THREAD

**Issue by Tieske** [lunarmodules/ldoc#64]
current documentation generation appears to be in code order, or random (haven't checked).

Is it possible to get it sorted alphabetically? In more complex docs its hard to find what you're looking for. See Penlight docs for example.

**Comment by alerque** [comment]
The initial issue here should be resolved now with the sort option availability. Custom sorting has a different tracking issue. If I'm missing anything comment for re-evaluation but this seems to be addressed.
