### ISSUE TITLE
Misinterpreted directory flag

### ISSUE THREAD

**Issue by craigbarnes** [lunarmodules/ldoc#74]
If I use the command:

```
ldoc -f markdown -d. -o name file.c
```

...for some reason the output goes to the directory `-.`, which is infuriatingly hard to delete with Unix utilities.

**Comment by alerque** [comment]
If you'd like please open an issue on the Penlight repository about supporting getopt-like parsing without spaces for single dash+letter flags,  but it isn't something we'll be tackling directly in this repository (unless we switch arg parsers for other reasons).
