### ISSUE TITLE
Default parameter value should be mentioned in the parameter documentation

### ISSUE THREAD

**Issue by agladysh** [lunarmodules/ldoc#78]
It is now mentioned in the function prototype, but IMHO it is not enough. It is better to collect all info about the parameter in the same place to avoid confusion.

I.e., for

```
-- @number[opt=1] level call stack level
```

instead of
- `level` ( **number** ) call stack level

we should get something like
- `level` ( **number** ) call stack level _(default: 1)_

(Exact wording can be improved, of course.)

**Comment by alerque** [comment]
This was been implemented in 7bb95e5.
