### ISSUE TITLE
Module names should not be used as value types

### ISSUE THREAD

**Issue by agladysh** [lunarmodules/ldoc#79]
Module, in general, is _not_ a type. It can be, accidentally, and some coding styles promote that, but it is not a reason to force that.

Example:

<pre>
-- @module lua-nucleo.table
...
-- @treturn table foo
</pre>

Yields a link to `lua-nucleo.table` module! o_O

**Comment by alerque** [comment]
Apparently fixed in d9d749f. If something is still missing let me know.
