### ISSUE TITLE
doc.md does not explain @\ syntax

### ISSUE THREAD

**Issue by agladysh** [lunarmodules/ldoc#82]
Either it is a special syntax, or some kind of broken attempt to escape text.

There are a few things like `@\{stdvars}`, `@\param[type=number]` etc., just search for `@\` in the rendered text.

**Comment by alerque** [comment]
This seems to be documented. Of course there are still holes in the docs and they could always use copy-editing. If you find something unclear feel free to submit a PR for the docs that clarify!

(If I missed something here feel free to comment for re-opening.)
