### ISSUE TITLE
Passing multiple files to "readme" in a table fails

### ISSUE THREAD

**Issue by rpavlik** [lunarmodules/ldoc#9]
I tried to pass multiple local human-written markdown files in this config: https://github.com/vance-group/vr-jugglua/blob/master/doc/generation/config.ld

None of them appear in the output, and no error appeared during generation.

**Comment by alerque** [comment]
I believe this feature request has been addressed since with the "topics" feature which recurses a directory of files. If this feature doesn't cover the use case please do comment back and we'll re-consider what might be required.
