### ISSUE TITLE
[BUG] @within tag not working properly

### ISSUE THREAD

**Issue by Tieske** [lunarmodules/ldoc#92]
having this section header that generates a section "Background workers"

```
--=============================================================================
--               BACKGROUND WORKERS
--=============================================================================

-------------------------------------------------------------------------------
-- Background workers.
-- @section workers

```

If I now use `@within workers` it results in an additional section called `workers`, and when I use `@within Background workers` it creates an additional section called `Background`.

It seems to take the first 'word' after `@within` and then look it up against the section DESCRIPTION instead of looking it up against the section NAME.

**Comment by alerque** [comment]
If the related PR above didn't actually address this let me know, but it looks like it was expected to resolve this issue.
